/**
 * Shared caption engine — tracks all generated captions across Create and Batch
 * to guarantee no duplicates until every variation is exhausted.
 *
 * Rules for all captions:
 * - Only reference real, shipped features
 * - No fabricated social proof, surveys, or community claims
 * - No made-up statistics or testimonials
 * - Questions to audience are genuine engagement prompts
 */

type Brand = 'affectly' | 'pacebrain';
type ContentType = 'quote' | 'tip' | 'carousel' | 'community' | 'promo';

// ── Caption pools ────────────────────────────────────────────────────────

const captionPools: Record<Brand, Record<ContentType, string[]>> = {
  affectly: {
    quote: [
      `Your study session should know you.\n\nAffectly asks how you're doing before each lesson. Feeling stressed? It slows the pace. Feeling energized? It goes deeper.\n\nLearning that adapts to your emotional state. That's how memory actually works.\n\nHow are you feeling before your next study session?`,
      `Learning that feels you.\n\nAffectly's AI detects your emotional state and reshapes the entire lesson in real time. Anxious? The material simplifies. Excited? It challenges you more.\n\nCognitive neuroscience shows emotions directly affect how we retain information. Affectly puts that science into practice.\n\nWhat subject would you learn differently if your mood was part of the equation?`,
      `Focus is not a switch you flip.\n\nIt's a byproduct of how you feel. When you're anxious, your brain narrows. When you're curious, it opens up.\n\nAffectly reads your emotional state and adjusts the lesson to match where your brain actually is. Not where you wish it was.\n\nTag someone who studies better when they feel good.`,
      `Emotions are the way you learn.\n\nResearch in cognitive neuroscience proves that emotional states directly impact memory retention and comprehension.\n\nAffectly uses this science. Check in with your mood, and the AI adapts your lesson pace, difficulty, and approach in real time.\n\nWhat if school had worked like this?`,
      `Work with your feelings, not against them.\n\nAffectly tracks your emotional patterns across sessions. Over time, you'll see when you learn best, what triggers your focus, and which moods help you retain more.\n\nYour emotional journey IS your learning journey.\n\nWhat time of day do you feel sharpest?`,
      `Your mood shapes your memory.\n\nWhen you're stressed, your brain prioritizes survival over learning. When you're calm, it absorbs more.\n\nAffectly checks in with your emotional state before each session and adjusts the lesson accordingly. Stressed? Simpler material. Calm? Deeper content.\n\nScience-backed learning that meets you where you are.`,
      `What if your study app actually listened to you?\n\nNot just what you type. How you feel.\n\nAffectly asks about your emotional state before every lesson. The AI uses that to adjust pace, difficulty, and content in real time.\n\nBecause a stressed brain and an energized brain need completely different approaches.\n\nWhen do you feel most ready to learn?`,
      `Self awareness is a study skill.\n\nMost people never track how their emotions affect their learning. Affectly does it automatically.\n\nCheck in before each session. See your patterns over time. Discover which emotional states lead to your best retention.\n\nKnowing yourself is the first step to studying smarter.`,
      `Cramming ignores how your brain works.\n\nYour brain encodes information differently depending on your emotional state. That's not opinion. That's neuroscience.\n\nAffectly builds every lesson around this principle. Check in with your mood. Let the AI adapt. Retain more with less effort.\n\nWhat's your biggest study frustration?`,
      `Stop forcing yourself to focus.\n\nStart understanding why you can't.\n\nAffectly's post-session analytics map your emotional journey through each study session. Over time, you'll see exactly which moods help you focus and which ones block retention.\n\nThe data is already there. You just need a tool that tracks it.`,
    ],
    tip: [
      `Emotions make you learn faster.\n\n1. Mood check in before every session: tell the AI how you feel and it adapts the lesson pace and difficulty to match your state.\n\n2. Upload your own documents: Affectly turns your PDFs and notes into personalized, emotion-aware lessons.\n\n3. Post-session analytics: see your emotional journey mapped out so you learn when and how you study best.\n\nWhich feature would help your study routine most? Save this.`,
      `Your flashcards should know how you feel.\n\nAffectly combines spaced repetition flashcards with emotional state tracking. The result? You review harder material when you're energized and lighter content when you're drained.\n\nMost apps treat you like a machine. Affectly treats you like a human.\n\nPlus you can upload your own materials and the AI builds custom flashcard decks from them.\n\nWhat are you studying right now? Drop it below.`,
      `Retain more of what you learn.\n\n1. Check in with your mood before studying. If you're stressed, start with simpler material to build momentum.\n\n2. Track your emotional patterns. Affectly shows you which moods lead to your best study sessions.\n\n3. Let the AI adapt. Affectly automatically adjusts lesson difficulty based on your emotional check in.\n\n4. Review your emotional journey after each session. Self awareness compounds over time.\n\nAffectly makes all of this automatic. Try it free.`,
      `How to study when you're stressed.\n\n1. Do an emotional check in. Affectly asks how you feel before each session — this isn't fluff, it shapes the entire lesson.\n\n2. Start with lighter material. The AI adjusts difficulty down when you're stressed so you build momentum instead of hitting walls.\n\n3. Keep sessions shorter. Better to retain 80% of a 15-minute session than 20% of an hour.\n\n4. Review your analytics after. Affectly tracks your emotional state alongside performance so you learn your own patterns.\n\nSave this for your next tough study day.`,
      `3 ways to use Affectly you might not know about.\n\n1. Upload any PDF, article, or notes file. The AI builds personalized lessons from YOUR material — not generic content.\n\n2. Check your post-session analytics. They show your emotional patterns over time so you can identify your peak learning windows.\n\n3. Use the flashcard builder. Affectly creates spaced repetition decks from your uploads and adapts review timing based on your mood and retention.\n\nWhich one are you trying first?`,
      `Your emotional check in is not optional.\n\nIt's the most important 10 seconds of your study session. Here's why:\n\nAffectly uses your mood to calibrate everything — lesson pace, content difficulty, and review intensity.\n\nSkip it, and you get a generic experience. Do it, and every session is built around how your brain is actually performing right now.\n\nThat's the difference between studying hard and studying smart.`,
      `Study smarter in 3 steps.\n\n1. Upload your own materials. PDFs, notes, articles — Affectly's AI turns them into structured lessons tailored to you.\n\n2. Check in with your mood. The AI adjusts the lesson based on whether you're energized, tired, stressed, or focused.\n\n3. Build flashcards from your uploads. Spaced repetition scheduling adapts based on your retention and emotional state.\n\nAll free to start. Link in bio.`,
      `Why your study routine is not working.\n\nYou're probably ignoring the biggest variable: how you feel.\n\nResearch shows emotional state directly impacts memory encoding. Studying while stressed uses a completely different neural pathway than studying while calm.\n\nAffectly tracks this automatically. Every session starts with a mood check in. Every lesson adapts in real time.\n\nStop brute-forcing your way through material.`,
      `Turn any document into a lesson.\n\nAffectly's AI takes your PDFs, notes, and articles and builds personalized, emotion-aware lessons from them.\n\n1. Upload your file\n2. The AI structures it into bite-sized lessons\n3. Check in with your mood\n4. The lesson adapts to match your state\n5. Build flashcard decks for review\n\nYour material. Your pace. Your emotional state considered.\n\nWhat would you upload first?`,
      `Post-session analytics you'll actually use.\n\nAfter every study session, Affectly shows you:\n\n- Your emotional state going in vs coming out\n- How your mood correlated with retention\n- Patterns across multiple sessions\n- Your peak learning windows over time\n\nMost apps just track time spent. Affectly tracks how you felt and how that affected what you learned.\n\nSelf awareness is a competitive advantage.`,
    ],
    carousel: [
      `Affectly adapts to you in real time.\n\n1. Check in with your mood before each lesson.\n2. The AI adjusts pace and difficulty based on how you feel.\n3. Upload any document and learn from it your way.\n4. Track your emotional patterns across sessions.\n5. Review your learning journey with post-session analytics.\n\nLearning that works with your brain, not against it. Save this for later.`,
      `5 things that make Affectly different.\n\n1. Emotional check ins shape every lesson before it begins.\n2. Upload your own PDFs, notes, or articles and the AI builds lessons from them.\n3. Spaced repetition flashcards that adapt based on your mood and retention.\n4. Real time difficulty adjustment so stressed days stay productive.\n5. Post-session analytics reveal your emotional learning patterns over time.\n\nBuilt on cognitive neuroscience. Free to start.`,
      `How Affectly works — a simple breakdown.\n\n1. Sign up free and upload your study materials.\n2. Before each session, do a quick emotional check in.\n3. The AI builds a lesson from your materials, calibrated to your mood.\n4. If you're stressed, it simplifies. If you're energized, it goes deeper.\n5. After the session, review analytics showing your emotional learning patterns.\n\nEvery session teaches you about yourself as much as the subject.`,
      `Your brain on Affectly.\n\n1. Mood check in: the AI asks how you feel. This takes 10 seconds.\n2. Lesson calibration: pace and difficulty adjust to match your emotional state.\n3. Your materials: upload PDFs and notes — the AI turns them into structured lessons.\n4. Flashcards: spaced repetition decks adapt based on mood and retention.\n5. Analytics: see which emotional states lead to your best learning over time.\n\nNeuroscience meets AI. Save this.`,
      `From stressed to productive in one session.\n\n1. Open Affectly and check in with how you're feeling.\n2. The AI detects stress and adjusts — shorter sections, simpler language, more breaks.\n3. You build momentum instead of hitting walls.\n4. Flashcard reviews focus on confidence-building material.\n5. Post-session analytics show that even stressed sessions produced retention.\n\nNot every study day feels great. Affectly makes every day count anyway.`,
      `Upload anything. Learn everything.\n\n1. Take a PDF, article, or notes file and upload it to Affectly.\n2. The AI breaks it into structured, bite-sized lessons.\n3. Check in with your mood — the lesson adapts accordingly.\n4. Build flashcard decks automatically from your uploaded content.\n5. Spaced repetition scheduling adjusts based on your retention patterns.\n\nYour material. Your emotional state. Your pace.`,
      `The Affectly study cycle.\n\n1. Upload your own study materials — PDFs, notes, articles.\n2. Check in with your mood before each session.\n3. The AI builds a lesson calibrated to how you feel right now.\n4. Review with emotion-aware flashcards after the lesson.\n5. Track your patterns in post-session analytics.\n6. Repeat — each session gets smarter as the AI learns your patterns.\n\nFree to start. Link in bio.`,
      `Why emotion-aware learning works.\n\n1. Stress narrows attention — Affectly detects this and simplifies content.\n2. Curiosity broadens it — the AI responds by going deeper.\n3. Fatigue lowers retention — sessions shorten and focus on review.\n4. Confidence accelerates learning — the AI increases challenge.\n5. Tracking these patterns over time reveals your optimal study conditions.\n\nThis is not theory. This is cognitive neuroscience applied to every session.`,
      `Affectly vs traditional study apps.\n\n1. Traditional: same lesson every time. Affectly: adapts based on your mood.\n2. Traditional: generic content. Affectly: built from YOUR uploaded materials.\n3. Traditional: fixed flashcard timing. Affectly: spacing adapts to mood and retention.\n4. Traditional: tracks time spent. Affectly: tracks emotional patterns and performance.\n5. Traditional: one size fits all. Affectly: every session is personalized.\n\nWhich approach sounds more effective?`,
      `5 emotional states Affectly responds to.\n\n1. Stressed — lessons simplify, sections shorten, pace slows.\n2. Energized — content goes deeper, challenges increase.\n3. Tired — focus shifts to review and lighter material.\n4. Anxious — difficulty drops, encouragement increases.\n5. Focused — the AI maximizes the window with dense, challenging content.\n\nYour emotional state is data. Affectly uses it.`,
    ],
    community: [
      `What if learning adapted to how you feel?\n\nMost study apps ignore the most important variable: your emotional state. Affectly was built on cognitive neuroscience research showing emotions directly shape memory and retention.\n\nCheck in with your mood. Let the AI adjust. Build self-aware learning habits over time.\n\nWould you study differently if your tools actually understood how you were feeling? Tell us below.`,
      `When do you learn best?\n\nMorning, afternoon, or late night? Stressed or relaxed? Energized or drained?\n\nMost people never figure this out because no tool tracks it. Affectly logs your emotional state before every session and maps it to your performance over time.\n\nThe goal: help you discover your own patterns so you can study smarter, not harder.\n\nDrop your best study time below.`,
      `What are you studying right now?\n\nAffectly works with any subject because you upload your own materials. PDFs, notes, articles — the AI turns them into personalized lessons.\n\nWhether it's med school anatomy, coding tutorials, or language learning, the emotional adaptation works the same way.\n\nDrop your subject below. We're curious what you're working on.`,
      `Honest question: do you track how you feel when you study?\n\nMost people don't. But research shows your emotional state is one of the strongest predictors of how much you'll retain.\n\nAffectly makes it simple — a quick mood check in before each session. The AI uses that data to adjust your lesson and track patterns over time.\n\nHave you ever noticed a connection between your mood and your study performance?`,
      `What's the hardest part of studying for you?\n\nStarting? Staying focused? Retaining what you read?\n\nAffectly approaches each of these differently based on your emotional state. If starting is hard because you're anxious, it eases you in. If focus drops because you're tired, it shortens sections.\n\nTell us your biggest study challenge below.`,
      `Name a study habit you wish you had.\n\nAffectly automates one that most people never build: emotional self-awareness while learning.\n\nEvery session starts with a mood check in. Over time, your analytics reveal which emotional states lead to your best retention.\n\nThat's a habit most people never develop on their own.\n\nWhat study habit would change things for you?`,
      `Do you study differently on good days vs bad days?\n\nYou should. Your brain literally processes information differently depending on your emotional state.\n\nAffectly handles this automatically. Check in with how you feel, and the AI adjusts the lesson — pace, difficulty, content depth — in real time.\n\nGood days go deeper. Hard days stay productive without burning you out.\n\nHow do you handle bad study days right now?`,
      `What would you upload to Affectly first?\n\nYou can upload any PDF, notes file, or article and the AI builds personalized lessons from it. Flashcards too.\n\nTextbook chapters? Lecture notes? Research papers? Certification material?\n\nDrop what you'd upload below.`,
      `Be honest: how many study apps have you tried and abandoned?\n\nMost study tools fail because they ignore how you feel. You open them tired, they throw hard material at you, and you close the app.\n\nAffectly starts every session with an emotional check in. The AI adapts so that even your worst days produce something useful.\n\nWhat made you quit your last study app?`,
      `If you could change one thing about how you study, what would it be?\n\nAffectly was built around one insight from cognitive neuroscience: emotions shape how we learn. Every feature — mood check ins, adaptive difficulty, emotional analytics — comes from that single principle.\n\nWhat would you change? Drop it below.`,
    ],
    promo: [
      `Learning that adapts to how you feel.\n\nAffectly is an AI-powered learning platform that personalizes every lesson based on your emotional state.\n\nHow it works:\n\n1. Check in with your mood before each session\n2. The AI adapts lesson pace and difficulty in real time\n3. Upload your own documents and learn from them\n4. Build flashcard decks with spaced repetition\n5. Track your emotional learning patterns over time\n\nFeeling stressed? Lessons slow down. Feeling energized? They go deeper.\n\nFree to start. Link in bio.`,
      `What if studying actually worked with your brain instead of against it?\n\nAffectly is a learning platform built on cognitive neuroscience. It reads your emotional state and reshapes every lesson to match how your brain actually processes information right now.\n\nStressed? Simpler material to build momentum. Energized? Deeper content to maximize retention.\n\nUpload any document. Build flashcards. Track your patterns. All personalized to you.\n\nTry it free today. Link in bio.`,
      `Your study app should adapt to you. Not the other way around.\n\nAffectly uses AI and cognitive neuroscience to personalize every session:\n\n- Emotional check ins before each lesson\n- Real time difficulty adjustment based on your mood\n- Upload your own PDFs, notes, and articles\n- Spaced repetition flashcards that adapt to your retention\n- Post-session analytics showing your emotional learning patterns\n\nFree to start. No credit card required. Link in bio.`,
      `Studying while stressed? There's a better way.\n\nAffectly detects when you're stressed and automatically adjusts your lesson — simpler content, shorter sections, and a pace that builds momentum instead of frustration.\n\nYou can also upload your own materials and the AI builds lessons from them. Plus spaced repetition flashcards that adapt to how you're feeling.\n\nBuilt on cognitive neuroscience. Free to start.\n\nLink in bio.`,
      `Upload any document. Get a personalized lesson.\n\nAffectly's AI takes your PDFs, notes, and articles and turns them into structured lessons that adapt to your emotional state.\n\n- Stressed? Content simplifies.\n- Energized? It goes deeper.\n- Tired? Sessions shorten and focus on review.\n\nPlus: spaced repetition flashcards built from your materials.\n\nYour content. Your mood. Your pace.\n\nFree to try. Link in bio.`,
      `Three reasons to try Affectly today.\n\n1. It adapts to your mood. Every lesson starts with an emotional check in. The AI adjusts difficulty and pace in real time.\n\n2. It uses YOUR materials. Upload PDFs, notes, or articles. The AI builds lessons and flashcards from them.\n\n3. It tracks your patterns. Post-session analytics show which emotional states lead to your best learning.\n\nBuilt on cognitive neuroscience. Free to start.\n\nLink in bio.`,
      `Stop studying harder. Start studying smarter.\n\nAffectly is an AI learning platform that adapts every session to your emotional state. Upload your own materials, check in with your mood, and let the AI build the right lesson for right now.\n\nSpaced repetition flashcards. Emotional analytics. Real time difficulty adjustment.\n\nAll based on cognitive neuroscience research.\n\nFree tier available. Link in bio.`,
      `Your brain learns differently every day.\n\nMonday morning you might be sharp and focused. Wednesday evening you might be drained.\n\nAffectly adjusts to this automatically. Every session starts with a mood check in, and the AI calibrates your lesson in real time.\n\nUpload your own study materials. Build flashcards. Track your emotional learning patterns.\n\nFree to start. Link in bio.`,
      `Most study apps waste your time.\n\nThey give you the same lesson whether you're energized or exhausted. The same difficulty whether you're confident or anxious.\n\nAffectly is different. It checks in with your emotional state and adapts everything — pace, difficulty, content depth — based on how your brain is actually performing.\n\nUpload your own materials. Build flashcards. See your patterns.\n\nTry it free. Link in bio.`,
      `Affectly: AI learning that understands how you feel.\n\nFeatures:\n- Emotional check in before every session\n- AI adapts lesson pace and difficulty in real time\n- Upload your own PDFs, notes, and articles\n- Spaced repetition flashcards (mood-aware)\n- Post-session emotional analytics\n- Track your learning patterns over time\n\nBuilt on cognitive neuroscience research. Free to start.\n\nLink in bio.`,
    ],
  },
  pacebrain: {
    quote: [
      `Stop guessing your race time.\n\nPaceBrain uses 6 peer-reviewed prediction models to forecast your finish time from 5K to ultra. Input a recent race result and get a science-backed prediction in 30 seconds.\n\nNo more calculators. No more guessing. Just data.\n\nWhat race are you predicting next?`,
      `Your Running DNA is unique.\n\nPaceBrain's Running DNA Analysis builds your personal endurance profile. It maps your strengths, identifies your limiters, and shows where your biggest gains are hiding.\n\nGeneric plans treat every runner the same. PaceBrain sees what makes you different.\n\nHave you discovered your Running DNA yet?`,
      `Smart pacing wins races.\n\nPaceBrain's Race Simulator shows your fitness trajectory and builds a pacing strategy from YOUR data. Not a calculator. Not someone else's splits. Your actual training history.\n\nRunners who race with a data-backed plan consistently outperform those who wing it.\n\nWhat's the last race where your pacing strategy worked perfectly?`,
      `Your heart rate is telling you something.\n\nPaceBrain's Heart Rate Intelligence breaks down your zones, tracks cardiac drift, and monitors recovery metrics across every session.\n\nWhen your easy runs creep into zone 3 without you noticing, PaceBrain flags it. That's the kind of insight that prevents overtraining and unlocks faster times.\n\nDo you train by heart rate or by feel?`,
      `Are you ready to train today?\n\nPaceBrain's RunSignal looks at your recent training load, recovery patterns, and performance trends to give you a clear daily readiness score: go hard, go easy, or rest.\n\nNo more guessing if you're recovered enough. No more guilt on rest days.\n\nDo you listen to your body or push through? Be honest.`,
      `Data doesn't lie. Your feelings might.\n\nYou feel ready to run hard. But your training load says you're under-recovered. PaceBrain's RunSignal catches this before you dig yourself into a hole.\n\nA daily readiness score based on your actual data — not how motivated your Instagram feed made you feel this morning.\n\nHave you ever ignored your body and regretted it?`,
      `Your easy pace might not be easy.\n\nIf your easy runs are consistently sitting in zone 3, you're accumulating fatigue without the aerobic benefit of true zone 2 work.\n\nPaceBrain's Heart Rate Intelligence flags this automatically. It tracks your zones across every session and shows you exactly where you're spending your time.\n\nWhat's your easy pace right now?`,
      `The best race plan is your own data.\n\nPaceBrain's Race Simulator takes your actual training history and projects your finish time for any distance from 5K to ultra.\n\nNo generic pace calculators. No copying someone else's splits. A projection built from what your body has actually done.\n\nWhat distance are you racing next?`,
      `Recovery is training.\n\nPaceBrain's RunSignal tracks your recovery patterns alongside your training load. It tells you whether today is a push day, an easy day, or a rest day.\n\nThe runners who respect recovery improve faster than the ones who grind every session.\n\nHow do you decide when to rest?`,
      `Know your strengths. Fix your limiters.\n\nPaceBrain's Running DNA Analysis looks at your training data and builds a profile of your unique endurance characteristics.\n\nAre you built for speed or distance? Where are your gains hiding? What's actually holding you back?\n\nGeneric training ignores all of this. PaceBrain starts with it.`,
    ],
    tip: [
      `3 features that change how you train.\n\n1. Race Predictions: input any recent race time and get finish forecasts across every distance from 5K to ultra, powered by 6 peer-reviewed models.\n\n2. AI Training Plans: weekly plans that adapt based on your actual progress. Miss a day? The plan restructures automatically.\n\n3. RunSignal: a daily readiness score that tells you whether to push hard, go easy, or recover.\n\nWhich one would change your training the most? Save this.`,
      `Nail your next race with PaceBrain.\n\n1. Sync your Strava or Garmin so PaceBrain has your full training history.\n2. Enter your goal race distance and date.\n3. Get a personalized training plan that adapts week to week.\n4. Use the Race Simulator to see your projected finish time as fitness builds.\n5. Check RunSignal each morning so you never overtrain.\n\nThe runners who follow a data-driven plan outperform the ones guessing their way through training blocks.\n\nWhat race are you training for? Drop it below.`,
      `Heart rate zones matter more than pace.\n\nPaceBrain's Heart Rate Intelligence shows you exactly which zones you're training in, tracks how your heart rate drifts during long runs, and monitors your recovery between sessions.\n\nHere's what most runners get wrong: running "easy" by pace but actually sitting in zone 3 the whole time. That's not easy. That's junk miles.\n\nPaceBrain catches this automatically and adjusts your training zones based on real data.\n\nFree tier includes GPS tracking and Strava sync. Link in bio.`,
      `How to use RunSignal to avoid overtraining.\n\n1. Open PaceBrain each morning and check your RunSignal score.\n2. Green means go — your body is recovered and ready for intensity.\n3. Yellow means caution — keep it easy or do a shorter session.\n4. Red means rest — take the day off or do light mobility work.\n\nRunSignal looks at your training load, recovery trends, and performance data. It's not a guess. It's your body's actual readiness.\n\nDo you check your readiness before every run?`,
      `Race predictions you can trust.\n\nPaceBrain uses 6 peer-reviewed prediction models — not a single formula. It cross-references multiple approaches to give you a realistic finish time forecast.\n\n1. Input a recent race result.\n2. Get predictions across every distance from 5K to ultra.\n3. See how your current training maps to your goal time.\n\n3 free predictions per month on the free tier. Strava sync included.\n\nWhat's your next target race time?`,
      `Your training plan should adapt to your life.\n\nMissed a workout? PaceBrain's AI Training Plans restructure automatically based on what you actually did that week.\n\nNo guilt. No falling behind. The plan adjusts to keep your training progression on track.\n\nThat's the difference between an AI plan and a static spreadsheet.\n\nHow often does life disrupt your training schedule?`,
      `How to read your Running DNA results.\n\n1. Sync your training data from Strava or Garmin.\n2. PaceBrain builds your personal endurance profile.\n3. It identifies whether you're naturally built for speed, endurance, or both.\n4. It shows your specific limiters — the areas where improvement will have the biggest impact.\n5. Your training plan targets these limiters automatically.\n\nGeneric plans can't do this. PaceBrain starts with who you are as a runner.\n\nSave this for when you set up your profile.`,
      `GPS tracking you don't need a watch for.\n\nPaceBrain's free tier includes GPS run tracking directly from your phone. No Garmin or Apple Watch required.\n\nPlus:\n- 3 race predictions per month\n- Strava sync\n- RunSignal daily readiness\n\nAlready have a watch? Sync it and PaceBrain uses that data too.\n\nNo excuses. Track your runs. Link in bio.`,
      `Stop training the same way every week.\n\n1. Your body adapts. The same workout produces diminishing returns.\n2. PaceBrain's AI plans adjust weekly based on your actual performance data.\n3. Hit your paces? Next week gets harder. Miss them? It recalibrates.\n4. The plan responds to what your body is doing, not what a spreadsheet says.\n\nThat's periodization without the guesswork.\n\nAre you still following the same plan from 3 months ago?`,
      `Cardiac drift is silently killing your long runs.\n\nYour heart rate creeps up even when pace stays constant. Over a long run, what started in zone 2 ends in zone 3. Most runners never notice.\n\nPaceBrain's Heart Rate Intelligence tracks drift automatically across every session. When your aerobic efficiency drops, you'll see it in the data.\n\nDo you monitor your heart rate during long runs?`,
    ],
    carousel: [
      `Train smarter with PaceBrain.\n\n1. Race Predictions powered by 6 peer-reviewed models, from 5K to ultra.\n2. AI Training Plans that adapt to your weekly progress automatically.\n3. Running DNA Analysis showing your unique endurance profile.\n4. Heart Rate Intelligence with zone tracking and drift detection.\n5. RunSignal daily readiness so you never overtrain.\n\nWhether you're running your first 5K or chasing an ultra PR, PaceBrain builds the plan around YOU.\n\nSave this for your next training block.`,
      `Your PaceBrain toolkit explained.\n\n1. Race Simulator: see your projected finish time improve as your training builds.\n2. Running DNA: discover whether you're built for speed, endurance, or both.\n3. Heart Rate Intelligence: track zones, detect drift, and monitor recovery.\n4. AI Plans: weekly training that restructures automatically when life happens.\n5. RunSignal: know whether today is a push day, easy day, or rest day.\n\nAll powered by your actual data. Not generic advice.`,
      `How PaceBrain builds your training plan.\n\n1. Sync Strava or Garmin — PaceBrain imports your full training history.\n2. Set your goal race distance and target date.\n3. The AI analyzes your fitness level and Running DNA.\n4. You get a weekly plan tailored to your strengths and limiters.\n5. Every week, the plan adapts based on what you actually ran.\n\nMiss a day? The plan restructures. Hit a PR? It recalibrates.\n\nSave this for when you're ready to get serious.`,
      `PaceBrain's Race Predictions — how they work.\n\n1. Input a recent race result at any distance.\n2. PaceBrain runs it through 6 peer-reviewed prediction models.\n3. You get finish time forecasts for every distance from 5K to ultra.\n4. The Race Simulator shows how your current training maps to your target.\n5. As you train, predictions update based on your latest data.\n\nScience-backed forecasts, not generic pace calculators.`,
      `5 signs you're overtraining.\n\n1. Your easy pace feels harder than usual — heart rate is elevated at the same speed.\n2. You're not improving despite running more miles.\n3. Sleep quality is dropping.\n4. Motivation is gone even though you care about your goal.\n5. Small injuries keep appearing.\n\nPaceBrain's RunSignal tracks your readiness daily and flags overtraining patterns before they become injuries.\n\nHow many of these apply to you right now?`,
      `From 5K to ultra — PaceBrain scales with you.\n\n1. Starting out? GPS tracking and RunSignal keep your training balanced.\n2. Racing a 10K? Race Predictions show your realistic finish time.\n3. Training for a half? AI plans adapt weekly to your progress.\n4. Marathon prep? Heart Rate Intelligence prevents overtraining.\n5. Going ultra? Running DNA reveals your endurance strengths and limiters.\n\nOne platform for every distance. Free tier available.`,
      `Heart Rate Intelligence — what PaceBrain tracks.\n\n1. Training zones: see exactly where you spend your time across all 5 zones.\n2. Cardiac drift: watch how your heart rate creeps up during long efforts.\n3. Recovery metrics: track how quickly your heart rate drops post-run.\n4. Zone violations: get flagged when easy runs drift into tempo territory.\n5. Trends over time: see your aerobic fitness improve session to session.\n\nYour heart rate data tells a story. PaceBrain reads it for you.`,
      `PaceBrain free tier vs premium.\n\n1. Free: GPS tracking from your phone. Premium: advanced route analytics.\n2. Free: 3 race predictions per month. Premium: unlimited predictions.\n3. Free: Strava sync. Premium: Strava + Garmin + full history import.\n4. Free: RunSignal daily readiness. Premium: detailed readiness breakdown.\n5. Free: basic training log. Premium: AI Training Plans that adapt weekly.\n\nStart free. Upgrade when you're ready. Link in bio.`,
      `The PaceBrain race day checklist.\n\n1. Check your final Race Prediction — know your realistic target time.\n2. Review your pacing strategy from the Race Simulator.\n3. Check RunSignal — confirm you're rested and ready.\n4. Warm up in zone 1-2 — PaceBrain shows your exact zones.\n5. Execute the plan. Trust the data you've built over weeks of training.\n\nSave this for race week.`,
      `Why your training plan keeps failing.\n\n1. It doesn't adapt. You miss a day and fall behind forever.\n2. It's generic. Same plan for a 20-mile-per-week runner and a 50-mile runner.\n3. It ignores your data. Your Strava is full of insights nobody is using.\n4. It doesn't check readiness. You run hard on days your body needs rest.\n5. It treats all runners the same. Your Running DNA is unique.\n\nPaceBrain fixes all five. Link in bio.`,
    ],
    community: [
      `Are you training with purpose or just logging miles?\n\nThere's a difference between running and training. Training means every session has a reason: your Strava syncs feed real data, your AI plan adapts weekly, and RunSignal tells you when to push and when to rest.\n\nPaceBrain was built for runners who refuse to guess.\n\nDrop your current training distance and goal time below.`,
      `What does your training week actually look like?\n\nEvery run should have a purpose. Easy days, tempo runs, long runs, rest days. But most runners just wing it.\n\nPaceBrain builds a plan that adapts to what you actually do each week. Miss a day? It restructures. Hit a PR? It recalibrates.\n\nWhether you're building a base or peaking for race day, the plan moves with you.\n\nShare your weekly mileage below.`,
      `What's your goal race this year?\n\n5K PR? First half marathon? A marathon you've been thinking about for years? An ultra you're not sure you're ready for?\n\nPaceBrain's Race Predictions cover every distance from 5K to ultra using 6 peer-reviewed models. Input a recent race time and see where you stand.\n\nDrop your goal race and distance below.`,
      `How do you decide when to rest?\n\nGut feeling? Scheduled rest day? When something hurts?\n\nPaceBrain's RunSignal gives you a daily readiness score based on your actual training load and recovery data. No guessing. No guilt.\n\nGreen = go. Yellow = easy. Red = rest.\n\nHow do you handle rest days right now?`,
      `What's the best running advice you've ever received?\n\nHere's one backed by data: your easy runs should actually be easy. Most runners run their easy days too fast, accumulating fatigue without the aerobic benefit.\n\nPaceBrain's Heart Rate Intelligence flags when your easy runs drift into zone 3. That's the kind of insight that prevents overtraining.\n\nShare your best running advice below.`,
      `Do you train by heart rate, pace, or feel?\n\nEach has pros and cons. Heart rate accounts for fatigue and conditions. Pace is consistent and measurable. Feel is intuitive but unreliable on hard days.\n\nPaceBrain tracks all three and shows you how they correlate across your training. Heart Rate Intelligence breaks down your zones, drift patterns, and recovery.\n\nWhat's your primary training metric?`,
      `What distance are you training for right now?\n\nPaceBrain builds AI training plans for any distance from 5K to ultra. The plan adapts weekly based on your actual runs — synced from Strava or Garmin.\n\nMiss a workout? The plan restructures. Nail a hard session? It progresses.\n\nDrop your distance and goal time below.`,
      `Be honest: do you follow a training plan?\n\nOr do you just run whatever feels right that day?\n\nThere's nothing wrong with running for fun. But if you have a race goal, a structured plan that adapts to your data will get you there faster than winging it.\n\nPaceBrain's AI plans restructure every week based on what you actually did. Not what you planned to do.\n\nAre you a plan follower or a freestyle runner?`,
      `What was your last race time?\n\nPaceBrain can take that result and predict your finish time across every distance from 5K to ultra. 6 peer-reviewed models. Not one formula — six.\n\nFree tier gives you 3 predictions per month plus Strava sync and RunSignal.\n\nDrop your last race distance and time below. Let's see what the models say.`,
      `What's the biggest mistake you've made in training?\n\nOvertraining? Going out too fast on race day? Skipping recovery? Following a plan that wasn't built for you?\n\nPaceBrain is designed to prevent all of these: RunSignal checks readiness, Race Simulator builds pacing strategies, and AI plans adapt to YOUR data.\n\nShare your training mistake below. We've all been there.`,
    ],
    promo: [
      `Stop guessing. Start training with data.\n\nPaceBrain is an AI running coach that predicts your race times and builds training plans that actually adapt to you.\n\nWhat you get:\n\n1. Race predictions from 5K to ultra using 6 peer-reviewed models\n2. AI training plans that restructure when life happens\n3. Running DNA Analysis showing your unique endurance profile\n4. Heart rate zone tracking with drift and recovery insights\n5. RunSignal daily readiness indicator\n6. Full Strava and Garmin sync\n\nFree tier available with GPS tracking, predictions, and Strava sync.\n\nLink in bio.`,
      `Every run should have a reason.\n\nPaceBrain is an AI running coach that turns your training data into a personalized plan, race predictions, and daily readiness insights.\n\nSync Strava or Garmin. Get race forecasts powered by 6 peer-reviewed models. Train with an AI plan that adapts every week based on what you actually did.\n\nFree tier: GPS tracking, 3 monthly predictions, Strava sync, and RunSignal.\n\nLink in bio.`,
      `Your next PR starts with better data.\n\nPaceBrain analyzes your training history and builds a plan designed to get you faster. Not a generic template. A plan built from your Running DNA, your heart rate data, and your actual performance.\n\nRace predictions across every distance. Daily readiness scoring. Automatic plan adjustments.\n\nSync Strava or Garmin to get started. Free tier available.\n\nLink in bio.`,
      `An AI running coach that actually adapts.\n\nPaceBrain builds your training plan from your data — then adjusts it every week based on what you actually ran.\n\nMiss a workout? The plan restructures around it. Hit every session? It progresses appropriately.\n\nPlus: race predictions using 6 peer-reviewed models, Heart Rate Intelligence, Running DNA Analysis, and daily readiness via RunSignal.\n\nFree to start. Link in bio.`,
      `Race predictions you can actually trust.\n\nPaceBrain doesn't use one formula. It uses 6 peer-reviewed prediction models and cross-references them to give you realistic finish time forecasts from 5K to ultra.\n\nInput a recent race result. See your projected times. Use the Race Simulator to track your fitness trajectory as you train.\n\n3 free predictions per month. Strava sync included. No credit card.\n\nLink in bio.`,
      `PaceBrain: smarter training for every runner.\n\nFeatures:\n- Race predictions from 5K to ultra (6 peer-reviewed models)\n- AI training plans that adapt weekly\n- Running DNA Analysis (personal endurance profile)\n- Heart Rate Intelligence (zones, drift, recovery)\n- RunSignal daily readiness score\n- GPS tracking from your phone\n- Strava and Garmin sync\n\nFree tier available. No watch required.\n\nLink in bio.`,
      `Train like you have a coach. Because now you do.\n\nPaceBrain's AI analyzes your training data and builds a plan tailored to your Running DNA. Every week, it adapts based on your actual performance.\n\nRace predictions tell you where you stand. RunSignal tells you when to push and when to rest. Heart Rate Intelligence keeps your zones honest.\n\nSync Strava or Garmin. Start free.\n\nLink in bio.`,
      `Most training plans fail because they don't adapt.\n\nYou miss one week and the whole thing falls apart. PaceBrain is different.\n\nThe AI restructures your plan every week based on what you actually did. Your training progresses at YOUR pace, not a spreadsheet's.\n\nPlus race predictions, heart rate analysis, and daily readiness scoring.\n\nFree tier: GPS tracking, 3 monthly predictions, Strava sync, RunSignal.\n\nLink in bio.`,
      `Your Strava data is full of insights nobody is using.\n\nPaceBrain connects to your Strava (or Garmin) and analyzes your training history to build race predictions, identify your Running DNA, and create a plan that adapts weekly.\n\nYour data is already there. PaceBrain turns it into a training strategy.\n\nSync your account. Get started free.\n\nLink in bio.`,
      `Running your first 5K or chasing an ultra PR? PaceBrain works for both.\n\nThe AI scales to your level. Beginners get structured plans with RunSignal readiness checks. Experienced runners get advanced analytics: Running DNA, cardiac drift tracking, and multi-model race predictions.\n\nOne platform. Every distance. Free to start.\n\nLink in bio.`,
    ],
  },
};

// ── Global dedup tracker (shared across Create and Batch) ────────────────

const generatedCaptions = new Set<string>();
const usedIndices: Record<string, Set<number>> = {};

export function generateCaption(brand: Brand, contentType: ContentType): string {
  const pool = captionPools[brand][contentType];
  const key = `${brand}-${contentType}`;
  if (!usedIndices[key]) usedIndices[key] = new Set();
  const used = usedIndices[key];

  // Reset if all used
  if (used.size >= pool.length) {
    used.clear();
  }

  // Find an index that hasn't been used AND whose text isn't in generatedCaptions
  const available = pool
    .map((_, i) => i)
    .filter(i => !used.has(i) && !generatedCaptions.has(pool[i]));

  // If all are in generatedCaptions but some indices unused, allow index-fresh ones
  const fallback = available.length > 0
    ? available
    : pool.map((_, i) => i).filter(i => !used.has(i));

  const candidates = fallback.length > 0 ? fallback : pool.map((_, i) => i);
  const idx = candidates[Math.floor(Math.random() * candidates.length)];

  used.add(idx);
  generatedCaptions.add(pool[idx]);
  return pool[idx];
}

export function resetCaptionHistory(): void {
  generatedCaptions.clear();
  for (const key of Object.keys(usedIndices)) {
    usedIndices[key].clear();
  }
}

// ── Hook text extraction ─────────────────────────────────────────────────

export function extractHookText(caption: string): string {
  if (!caption.trim()) return '';
  // Remove emojis for cleaner hook text
  const cleanCaption = caption.replace(/[\u{1F600}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}]/gu, '').trim();
  const lines = cleanCaption.split('\n').map(l => l.trim()).filter(Boolean);
  if (lines.length === 0) return '';

  // First line is the hook candidate
  let hook = lines[0];

  // Remove trailing punctuation
  hook = hook.replace(/[.:,]\s*$/, '');

  // If hook contains a question mark, use it as natural endpoint
  const questionMark = hook.indexOf('?');
  if (questionMark > 5 && questionMark <= 55) {
    return hook.substring(0, questionMark + 1);
  }

  // Truncate to max 45 chars at a word boundary for clean display
  if (hook.length > 45) {
    // Try to find a natural break (comma, period) first
    const comma = hook.indexOf(',');
    if (comma > 10 && comma <= 45) {
      return hook.substring(0, comma);
    }
    const period = hook.indexOf('.');
    if (period > 10 && period <= 45) {
      return hook.substring(0, period);
    }
    // Otherwise truncate at word boundary
    const truncated = hook.substring(0, 45);
    const lastSpace = truncated.lastIndexOf(' ');
    return lastSpace > 10 ? truncated.substring(0, lastSpace) : truncated;
  }

  return hook;
}
